### ISSUE TITLE
Thumbnail Disappears?

### ISSUE THREAD

**Issue by jonjon2420** [Tortellio/LobbyEdit#1]
For whatever reason the thumbnail completely disappears when using this plugin, the custom config works just fine but the thumbnail is gone, I'm sure the creator has long ago left this project, as everyone in the Unturned modding community has, so this is here just so anyone can see the issues with the plugin.

**Comment by Tortellio** [comment]
#7fda419ce7b128fa49e9a91e80287a4d1e2365b6
Fixed
